//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// All assembly attributes have been removed to avoid duplication errors.
// If you need to set assembly attributes, use the .csproj file or project properties.
